name: minecraft-server

services:
  application:
    build:
      context: ./../
      dockerfile: ./docker/dockerfile
    volumes:
      - data:/opt/minecraft-server/
    ports:
      - 25565:25565

volumes:
  data:
    name: minecraft-server-data

networks:
  default:
    name: minecraft-server-network # can be changed to Traefik one in the future