FROM alpine:3.21.3 AS builder
WORKDIR /opt/minecraft-server/

RUN apk add --no-cache curl 
RUN curl -OJ https://meta.fabricmc.net/v2/versions/loader/1.21.4/0.16.10/1.0.1/server/jar
RUN echo "eula=true" > eula.txt

COPY ./configuration/ /opt/minecraft-server/

FROM openjdk:21 AS runner
WORKDIR /opt/minecraft-server/

COPY --from=builder /opt/minecraft-server/ /opt/minecraft-server/

ENTRYPOINT ["java", "-Xmx8G", "-jar", "fabric-server-mc.1.21.4-loader.0.16.10-launcher.1.0.1.jar", "nogui"]
